#! /bin/bash

rm -f *.tex~ elsarticle-template.mtc1 elsarticle-template.aux elsarticle-template.dvi elsarticle-template.lof elsarticle-template.log elsarticle-template.out elsarticle-template.lot elsarticle-template.toc elsarticle-template.brf elsarticle-template.maf elsarticle-template.mtc elsarticle-template.mtc0 elsarticle-template.nlo elsarticle-template.end elsarticle-template.spl elsarticle-templateNotes.bib

pdflatex -shell-escape elsarticle-template.tex
bibtex elsarticle-template
pdflatex -shell-escape elsarticle-template.tex
pdflatex -shell-escape elsarticle-template.tex

rm -f *.tex~ elsarticle-template.mtc1 elsarticle-template.aux elsarticle-template.dvi elsarticle-template.lof elsarticle-template.log elsarticle-template.out elsarticle-template.lot elsarticle-template.toc elsarticle-template.brf elsarticle-template.maf elsarticle-template.mtc elsarticle-template.mtc0 elsarticle-template.nlo elsarticle-template.end elsarticle-template.spl elsarticle-templateNotes.bib

